version: 0.0
os: linux
files:
  - source: /
    destination: /opt/deployment/
    
hooks:
  AfterInstall:
    - location: scripts/set_permission.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deploy.sh
