version: 0.0
os: linux
files:
  - source: /
    destination: /opt/deployment/
    
hooks:
  AfterInstall:
    - location: /opt/deployment/scripts/set_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /opt/deployment/deploy.sh
      timeout: 300
      runas: root
