version: 0.0
os: linux
files:
  - source: scripts
    destination: /home/ubuntu/trailcicd
    
hooks:
  AfterInstall:
    - location: /opt/deployment/scripts/set_permission.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /opt/deployment/scripts/deploy.sh
