version: 0.0
os: linux
files:
  - source: source
    destination: /opt/deployment/
    
hooks:
  AfterInstall:
    - location: /opt/deployment/scripts/set_permission.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /opt/deployment/scripts/deploy.sh
