version: 0.0
os: linux
   
hooks:
  AfterInstall:
    - location: scripts/set_permission
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deploy
      timeout: 300
      runas: root
